// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: counter.sql

package db

import (
	"context"
)

const changeCounter = `-- name: ChangeCounter :one
UPDATE counters
SET value = value + $1,
    updated_at = now()
WHERE id = 1
  AND value + $1 >= 0
RETURNING id, value, updated_at
`

func (q *Queries) ChangeCounter(ctx context.Context, delta int32) (Counter, error) {
	row := q.db.QueryRow(ctx, changeCounter, delta)
	var i Counter
	err := row.Scan(&i.ID, &i.Value, &i.UpdatedAt)
	return i, err
}

const getCounter = `-- name: GetCounter :one
SELECT id, value, updated_at
FROM counters
WHERE id = 1
`

func (q *Queries) GetCounter(ctx context.Context) (Counter, error) {
	row := q.db.QueryRow(ctx, getCounter)
	var i Counter
	err := row.Scan(&i.ID, &i.Value, &i.UpdatedAt)
	return i, err
}

const resetCounter = `-- name: ResetCounter :one
UPDATE counters
SET value = 0,
    updated_at = now()
WHERE id = 1
RETURNING id, value, updated_at
`

func (q *Queries) ResetCounter(ctx context.Context) (Counter, error) {
	row := q.db.QueryRow(ctx, resetCounter)
	var i Counter
	err := row.Scan(&i.ID, &i.Value, &i.UpdatedAt)
	return i, err
}
