// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Counter struct {
	ID        int32              `json:"id"`
	Value     int32              `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
